### ISSUE TITLE
How to use these files?

### ISSUE THREAD

**Issue by 461353349** [heger-valter/CAD#1]
How to use these files?

**Comment by heger-valter** [comment]
You have to have model in Irato (Constructive Solid Geometry) format. Then it converts it to STEP-Faceted representation, and serializes it to STEP's file format.  I would suggest creating a body in STEP-CSG and exporting to STEP-Faceted .
Similarly, some functionality exists to write out simple STEP Advanced Representation.  This needs more work.

**Comment by 461353349** [comment]
I have not found what is the Irato format. STEP-CSG imports or exports the model using Opencascad. 
I want to read stp file format  and write stl file format without third-party library. But I donnot know how   to do it, Can you give me some advice?

**Comment by heger-valter** [comment]
I don't have Irato format as it is proprietary.  Probably best to start with a simple cube in STEP-CSG format.  Need to rewrite code using STEP instead of Irato.  Once it works for a box, work on a cylinder, Then model cube with a hole drilled out.

**Comment by 461353349** [comment]
Thanks!
